### PR TITLE
Russian translation of the flyer #385

### PR DESCRIPTION
**Pull request by v1docq47**
Translate:

- flyer_ru.pdf 100%
- flyer_ru.sla 100%

Calling to review:
@monerorus @LvMsterfild @AJIekceu4 @TheFuzzStone

### CODE REVIEW

**Comment by erciccione** [comment]
Thanks for this @v1docq47 , but can you open the same PR in monero-ecosystem/monero-meetup-kit-localization ?

**Comment by v1docq47** [comment]
@erciccione Yes, I will do it now. If necessary, you can close this PR. Thanks!

**Comment by erciccione** [comment]
Thanks. Will close this once the new PR will be opened

**Comment by v1docq47** [comment]
@erciccione , PR in monero-ecosystem
https://github.com/monero-ecosystem/monero-meetup-kit-localization/pull/32

**Pull request closed without merging**
